services:
  - type: web
    name: swap-skills-bot
    env: python
    plan: free
    region: oregon
    runtime: python3.11
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
